### ISSUE TITLE
Internet Usage

### ISSUE THREAD

**Issue by PatrickDuncan** [PatrickDuncan/cleansio#71]
In real-time mode Google Cloud Speech will be constantly called over and over again in a very short period of time.

- [ ] Monitor internet traffic while using Cleansio on a long audio file
- [ ] Record download bandwidth
- [ ] Record upload bandwidth
