### ISSUE TITLE
Overlapping Chunk

### ISSUE THREAD

**Issue by PatrickDuncan** [PatrickDuncan/cleansio#73]
To improve the accuracy of #70, use an overlapping audio chunk.

Right now we're sequentially breaking up the audio file into 5 second chunks. The problem with this is the lyrics at the border between 2 audio chunks is cut off. By using another audio chunk that is 2.5 seconds ahead we can avoid this issue.

- [x] Create another chunk 2.5 seconds after the current chunk
- [x] Transcribe with GCS
- [x] Use that transcription to improve the accuracy of the current chunk
- [x] Discard the overlapping chunk
